# .github/workflows/douban.yml
name: douban
on:
  schedule:
  - cron: "20 * * * *"
  watch:
    types: [started]

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: conge
        type: book
        format: csv
        dir: ./_data

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: conge
        type: movie
        format: csv
        dir: ./_data
    - name: music
      uses: lizheming/doumark-action@master
      with:
        id: conge
        type: music
        format: csv
        dir: ./_data

    - name: Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'chore: update douban data'
        add: './_data'
